<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shockky.SourceGeneration\Shockky.SourceGeneration.csproj"/>
    <ProjectReference Include="..\Shockky\Shockky.csproj" />
  </ItemGroup>

</Project>