<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shockky\Shockky.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Data\d101_empty.dcr" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Data\d101_empty.dir" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
