//HintName: SizeOverrideItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="SizeOverrideItem"/>
partial class SizeOverrideItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        output.WriteInt32BigEndian(Id);
    }
}