//HintName: WriteOverrideItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="WriteOverrideItem"/>
partial class WriteOverrideItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += 4;

        return size;
    }
}