//HintName: HeaderConditionItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="HeaderConditionItem"/>
partial class HeaderConditionItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public HeaderConditionItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        int bodySize = input.ReadInt32BigEndian();
        Header = global::HeaderConditionItem.ConditionHeaderData.Read(ref input, context, bodySize);

    }

    public HeaderConditionItem() { }

    public static HeaderConditionItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}