//HintName: ItemWithHeader+HeaderData.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="ItemWithHeader"/>
partial class ItemWithHeader
{
    /// <inheritdoc cref="HeaderData"/>
    partial class HeaderData
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int GetBodySize(global::Shockky.IO.WriterOptions options)
        {
            int size = sizeof(int);

            size += 8;

            return size;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
        {
            WriteTo(ref output, options, GetBodySize(options));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        internal void WriteTo(ref global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options, int bodySize)
        {
            output.WriteInt32BigEndian(Version);
            output.WriteInt32BigEndian(Length);
        }
    }
}