//HintName: ItemWithHeader.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="ItemWithHeader"/>
partial class ItemWithHeader
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public ItemWithHeader(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        int bodySize = input.ReadInt32BigEndian();
        Header = global::ItemWithHeader.HeaderData.Read(ref input, context, bodySize);

        Data = input.ReadInt32BigEndian();
    }

    public ItemWithHeader() { }

    public static ItemWithHeader Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}