//HintName: StringEntriesItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="StringEntriesItem"/>
partial class StringEntriesItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += 30;
        size += Name is not null ? global::Shockky.IO.ShockwaveWriter.GetPStringSize(Name) : 0;
        size += Path is not null ? global::Shockky.IO.ShockwaveWriter.GetCStringSize(Path) : 0;
        size += Script is not null ? global::Shockky.IO.ShockwaveWriter.GetFixedStringSize(Script) : 0;
        size += Value is not null ? 4 : 0;

        return size;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        global::System.Span<int> entrySizes = [
            Name is not null ? global::Shockky.IO.ShockwaveWriter.GetPStringSize(Name) : 0,
            Path is not null ? global::Shockky.IO.ShockwaveWriter.GetCStringSize(Path) : 0,
            Script is not null ? global::Shockky.IO.ShockwaveWriter.GetFixedStringSize(Script) : 0,
            0,
            0,
            Value is not null ? 4 : 0,
            0
        ];
        global::Shockky.IO.OffsetTable.CreateAndWriteTo(entrySizes, ref output);

        if (Name is not null)
        {
            output.WritePString(Name);
        }
        if (Path is not null)
        {
            output.WriteCString(Path);
        }
        if (Script is not null)
        {
            output.WriteFixedString(Script);
        }
        if (Value is not null)
        {
            output.WriteInt32BigEndian(Value.GetValueOrDefault());
        }
    }
}