//HintName: BigEndianItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="BigEndianItem"/>
partial class BigEndianItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public BigEndianItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32BigEndian();
        Value = input.ReadInt16BigEndian();
        Flags = input.ReadByte();
    }

    public BigEndianItem() { }

    public static BigEndianItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}