//HintName: EnumItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="EnumItem"/>
partial class EnumItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += 2;

        return size;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        output.WriteUInt16BigEndian((ushort)Kind);
    }
}