//HintName: EnumItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="EnumItem"/>
partial class EnumItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public EnumItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Kind = (global::SmallEnum)input.ReadUInt16BigEndian();
    }

    public EnumItem() { }

    public static EnumItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}