//HintName: LocalEndianItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="LocalEndianItem"/>
partial class LocalEndianItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public LocalEndianItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        bool previousReverseEndianness = input.ReverseEndianness;
        input.ReverseEndianness = false;
        try
        {
            Id = input.ReadInt32BigEndian();
        }
        finally
        {
            input.ReverseEndianness = previousReverseEndianness;
        }
    }

    public LocalEndianItem() { }

    public static LocalEndianItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}