//HintName: SizeOverrideItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="SizeOverrideItem"/>
partial class SizeOverrideItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public SizeOverrideItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32BigEndian();
    }

    public SizeOverrideItem() { }

    public static SizeOverrideItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}