//HintName: LittleEndianSerializableItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="LittleEndianSerializableItem"/>
partial class LittleEndianSerializableItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += 6;

        return size;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        output.WriteInt32LittleEndian(Id);
        output.WriteUInt16LittleEndian(Count);
    }
}