//HintName: UnsupportedItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="UnsupportedItem"/>
partial class UnsupportedItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public UnsupportedItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Value = default(object);
    }

    public UnsupportedItem() { }

    public static UnsupportedItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}