//HintName: ItemWithEntries.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="ItemWithEntries"/>
partial class ItemWithEntries
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public ItemWithEntries(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        global::Shockky.IO.OffsetTable offsets = global::Shockky.IO.OffsetTable.Read(ref input);

        for (int entryIndex = 0; entryIndex < offsets.Length; entryIndex++)
        {
            int entrySize = offsets.GetEntrySize(entryIndex);
            if (entrySize == 0) continue;

            int entryStart = input.Position;
            switch (entryIndex)
            {
                case 0:
                    FirstEntry = input.ReadInt32BigEndian();
                    break;
                case 1:
                    SecondEntry = input.ReadInt16BigEndian();
                    break;
                default:
                    input.Advance(entrySize);
                    break;
            }

            int consumed = input.Position - entryStart;
            if (consumed < entrySize)
            {
                input.Advance(entrySize - consumed);
            }
        }

    }

    public ItemWithEntries() { }

    public static ItemWithEntries Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}