//HintName: BigEndianSerializableItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="BigEndianSerializableItem"/>
partial class BigEndianSerializableItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += 6;
        size += global::Shockky.IO.ShockwaveWriter.GetPStringSize(Name);

        return size;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        output.WriteInt32BigEndian(Id);
        output.WriteUInt16BigEndian(Count);
        output.WritePString(Name);
    }
}