//HintName: LittleEndianItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="LittleEndianItem"/>
partial class LittleEndianItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public LittleEndianItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32LittleEndian();
        Value = input.ReadUInt16LittleEndian();
    }

    public LittleEndianItem() { }

    public static LittleEndianItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}