//HintName: LittleEndianSerializableItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="LittleEndianSerializableItem"/>
partial class LittleEndianSerializableItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public LittleEndianSerializableItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32LittleEndian();
        Count = input.ReadUInt16LittleEndian();
    }

    public LittleEndianSerializableItem() { }

    public static LittleEndianSerializableItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}