//HintName: ItemWithHeader+HeaderData.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="ItemWithHeader"/>
partial class ItemWithHeader
{
    /// <inheritdoc cref="HeaderData"/>
    partial class HeaderData
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        public HeaderData(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context, int bodySize)
        {
            Version = input.ReadInt32BigEndian();
            Length = input.ReadInt32BigEndian();
        }

        public HeaderData() { }

        public static HeaderData Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context, int bodySize) => new(ref input, context, bodySize);
    }
}