//HintName: BigEndianSerializableItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="BigEndianSerializableItem"/>
partial class BigEndianSerializableItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public BigEndianSerializableItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32BigEndian();
        Count = input.ReadUInt16BigEndian();
        Name = input.ReadPString();
    }

    public BigEndianSerializableItem() { }

    public static BigEndianSerializableItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}