//HintName: HeaderConditionItem.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="HeaderConditionItem"/>
partial class HeaderConditionItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int GetBodySize(global::Shockky.IO.WriterOptions options)
    {
        int size = 0;

        size += Header.GetBodySize(options);

        return size;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
    {
        int headerBodySize = Header.GetBodySize(options);
        output.WriteInt32BigEndian(headerBodySize);
        Header.WriteTo(ref output, options, headerBodySize);
    }
}