//HintName: HeaderConditionItem+ConditionHeaderData.Write.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="HeaderConditionItem"/>
partial class HeaderConditionItem
{
    /// <inheritdoc cref="ConditionHeaderData"/>
    partial class ConditionHeaderData
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public int GetBodySize(global::Shockky.IO.WriterOptions options)
        {
            int size = sizeof(int);

            size += 12;
            if (ScriptContextNum is not null)
            {
                size += 4;
            }

            return size;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void WriteTo(global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options)
        {
            WriteTo(ref output, options, GetBodySize(options));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        internal void WriteTo(ref global::Shockky.IO.ShockwaveWriter output, global::Shockky.IO.WriterOptions options, int bodySize)
        {
            output.WriteZeroes(4);
            output.WriteInt32BigEndian(Flags);
            output.WriteUInt32BigEndian(Options);
            if (bodySize >= 20)
            {
                output.WriteInt32BigEndian(ScriptContextNum.GetValueOrDefault());
            }
        }
    }
}