//HintName: WriteOverrideItem.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="WriteOverrideItem"/>
partial class WriteOverrideItem
{
    [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public WriteOverrideItem(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context)
    {
        Id = input.ReadInt32BigEndian();
    }

    public WriteOverrideItem() { }

    public static WriteOverrideItem Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context) => new(ref input, context);
}