//HintName: HeaderConditionItem+ConditionHeaderData.Read.g.cs
// <auto-generated/>
#pragma warning disable

/// <inheritdoc cref="HeaderConditionItem"/>
partial class HeaderConditionItem
{
    /// <inheritdoc cref="ConditionHeaderData"/>
    partial class ConditionHeaderData
    {
        [global::System.CodeDom.Compiler.GeneratedCode("ShockwaveItemGenerator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        public ConditionHeaderData(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context, int bodySize)
        {
            input.Advance(4);
            Flags = input.ReadInt32BigEndian();
            Options = input.ReadUInt32BigEndian();
            if (bodySize >= 20)
                ScriptContextNum = input.ReadInt32BigEndian();
        }

        public ConditionHeaderData() { }

        public static ConditionHeaderData Read(ref global::Shockky.IO.ShockwaveReader input, global::Shockky.IO.ReaderContext context, int bodySize) => new(ref input, context, bodySize);
    }
}