namespace Shockky.Lingo.Instructions
{
    public enum OPCode
    {
        Return = 0x01,
        PushInt0 = 0x03,
        Multiple,
        Add,
        Substract,
        Divide,
        Modulo,
        Inverse,
        JoinString,
        JoinPadString,
        LessThan,
        LessThanEquals,
        NotEqual,
        Equals,
        GreaterThan,
        GreaterEquals,
        And,
        Or,
        Not,
        ContainsString,
        StartsWith,
        SplitString,
        LightString,
        OnToSprite,
        IntoSprite,
        CastString,
        StartObject,
        StopObject,
        WrapList,
        NewPropList,

        Swap = 0x21,
        ExecuteJavascript = 0x26,

        //Multi

        PushInt = 0x41,
        NewArgList,
        NewList,
        PushConstant,
        PushSymbol,
        PushObject,
        Op_47,
        Op_48,
        GetGlobal,
        GetProperty,
        GetParameter,
        GetLocal,
        SetGlobal = 0x4f,
        SetProperty,
        SetParameter,
        SetLocal,
        Jump,
        EndRepeat,
        IfTrue,
        CallLocal,
        CallExternal,
        CallObjOld, //?
        Op_59,
        Op_5a,
        Op_5b,
        Get,
        Set,
        GetMovieProp = 0x5f,
        SetMovieProp,
        GetObjProp,
        SetObjProp,
        Op_63,
        Dup,
        Pop,
        GetMovieInfo,
        CallObj,
        PushInt2 = 0x6e,
        PushInt3,
        GetSpecial, //TODO:
        PushFloat,
        Op_72,
        Op_7d = 0x7d
    }
}